copy macros.sqf common /Y
copy macros.sqf common\func /Y
copy macros.sqf common\func\net /Y
copy macros.sqf common\client /Y
copy macros.sqf common\client\func /Y
copy macros.sqf common\server /Y
copy macros.sqf common\server\func /Y
copy macros.sqf fsms /Y
copy macros.sqf dialogs /Y

copy setup.sqf common /Y
copy setup.sqf common\func /Y
copy setup.sqf common\func\net /Y
copy setup.sqf common\client /Y
copy setup.sqf common\client\func /Y
copy setup.sqf common\server /Y
copy setup.sqf common\server\func /Y
copy setup.sqf fsms /Y
copy setup.sqf dialogs /Y